services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest # Use a specific version for production
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin_password # Change this in production!
      KC_DB: dev-file # Use PostgreSQL/MySQL/MariaDB in production, along with volumes.
      KC_HOSTNAME: localhost
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_STRICT: "false" # Set to true in a production, reverse-proxy setup.
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-realm-config:/opt/keycloak/data/import # Mount the import directory
    command:
      - start-dev
      - --import-realm # Import the realm on startup
